---
- name: Create multiple Ubuntu VMs from inventory
  hosts: localhost  # Kör allt på localhost
  connection: local
  gather_facts: false
  
  vars:
    vm_list:
      - name: "ubuntu1"
        id: 201
        memory: 2048
        cores: 2
      - name: "ubuntu2"
        id: 202
        memory: 2048
        cores: 2
      - name: "ubuntu3"
        id: 203
        memory: 2048
        cores: 2

  tasks:
    - name: Create VMs one by one
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        clone: "{{ template_id }}"
        vmid: "{{ template_id }}"
        newid: "{{ item.id }}"
        full: yes
        name: "{{ item.name }}"
        node: pve
        storage: local-lvm
        format: qcow2
        memory: "{{ item.memory }}"
        cores: "{{ item.cores }}"
        timeout: 600  # 10 minuter timeout
      loop: "{{ vm_list }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Start all VMs
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        vmid: "{{ item.id }}"
        state: started
      loop: "{{ vm_list }}"
      loop_control:
        label: "Starting {{ item.name }}"
