---
- name: Create multiple Ubuntu VMs from inventory
  hosts: localhost  # <--- BYT TILL localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Create VMs one by one
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        clone: "{{ template_id }}"
        vmid: "{{ template_id }}"
        newid: "{{ item.vm_id }}"
        full: yes
        name: "{{ item.vm_name }}"
        node: pve
        storage: local-lvm
        format: qcow2
        memory: "{{ item.memory }}"
        cores: "{{ item.cores }}"
        timeout: 600
      loop: "{{ groups['ubuntu_vms'] | map('extract', hostvars, ['vm_id', 'vm_name', 'memory', 'cores']) | list }}"
      loop_control:
        label: "{{ item.vm_name }}"
      register: clone_results

    - name: Start all VMs
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        vmid: "{{ item.vm_id }}"
        state: started
      loop: "{{ groups['ubuntu_vms'] | map('extract', hostvars, 'vm_id') | list }}"
