---
- name: Installera Crafty Controller
  hosts: linux_servers
  become: true
  tasks:
    - name: Ta bort befintlig crafty-installer katalog
      file:
        path: /tmp/crafty-installer-4.0
        state: absent

    - name: Klona crafty installer
      git:
        repo: https://gitlab.com/crafty-controller/crafty-installer-4.0.git
        dest: /tmp/crafty-installer-4.0
        clone: yes
        force: yes

    - name: Installera Crafty Controller
      shell: "cd /tmp/crafty-installer-4.0 && sudo ./install_crafty.sh <<< $'y\ny\ny\nmaster\ny'"
      args:
        executable: /bin/bash
      timeout: 100
      register: install_result

    - name: Visa installationsresultat
      debug:
        var: install_result

    - name: Aktivera och starta Crafty service
      systemd:
        name: crafty.service
        enabled: yes
        state: started
        daemon_reload: yes
      when: install_result.rc == 0

    - name: Kontrollera status på Crafty service
      systemd:
        name: crafty.service
      register: crafty_service_status
      when: install_result.rc == 0

    - name: Visa Crafty service status
      debug:
        msg: "Crafty service status: {{ crafty_service_status.status }}"
      when: install_result.rc == 0

    - name: Kontrollera om credentials-filen finns
      stat:
        path: /var/opt/minecraft/crafty/crafty-4/app/config/default-creds.txt
      register: creds_file
      when: install_result.rc == 0

    - name: Läsa Crafty default credentials
      slurp:
        src: /var/opt/minecraft/crafty/crafty-4/app/config/default-creds.txt
      register: crafty_creds
      when: creds_file.stat.exists and install_result.rc == 0

    - name: Visa Crafty credentials
      debug:
        msg: "Crafty Default Credentials:\n{{ crafty_creds.content | b64decode }}"
      when: creds_file.stat.exists and install_result.rc == 0
