---
- name: Check if template 105 exists
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    proxmox_host: "{{ SEMAPHORE_PROXMOX_HOST }}" 
    proxmox_user: "{{ SEMAPHORE_PROXMOX_USER }}"
    proxmox_password: "{{ SEMAPHORE_PROXMOX_PASSWORD }}"
    validate_certs: false
    
  tasks:
    - name: Get information about VM 105
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: "{{ validate_certs }}"
        node: "pve"
        vmid: 105
        state: current
      register: vm_info
      ignore_errors: yes

    - name: Display VM 105 info
      debug:
        var: vm_info

    - name: Check template status
      debug:
        msg: |
          VM 105 exists: {{ vm_info is succeeded }}
          Is template: {{ vm_info.template if vm_info is succeeded else 'Unknown' }}
