---
- name: Create Ubuntu VM from template in Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    proxmox_host: "{{ SEMAPHORE_PROXMOX_HOST }}" 
    proxmox_user: "{{ SEMAPHORE_PROXMOX_USER }}"
    proxmox_password: "{{ SEMAPHORE_PROXMOX_PASSWORD }}"
    validate_certs: false
    
  tasks:
    - name: Display which user is being used
      debug:
        msg: "Using Proxmox user: {{ proxmox_user }}"
        
    - name: Create Ubuntu VM by cloning template
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: "{{ validate_certs }}"
        
        node: "pve"
        name: "ubuntu-test-from-ansible"
        vmid: 9999
        clone: 105
        full: yes
        memory: 2048
        cores: 2
        state: started
        
      register: vm_creation_result

    - name: Display VM creation result
      debug:
        var: vm_creation_result
