---
- name: Create VM from template using internet example
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Clone template to new VM
      community.general.proxmox_kvm:
        api_user: "{{ SEMAPHORE_PROXMOX_USER }}"
        api_password: "{{ SEMAPHORE_PROXMOX_PASSWORD }}"
        api_host: "{{ SEMAPHORE_PROXMOX_HOST }}"
        clone: 109  # Din template
        vmid: 109   # Käll-VM ID
        newid: 200 # Nytt VM ID
        full: yes
        name: "test1"  # Namn på nya VM
        node: pve
        storage: local-lvm
        format: qcow2

    - name: Start the new VM
      community.general.proxmox_kvm:
        api_user: "{{ SEMAPHORE_PROXMOX_USER }}"
        api_password: "{{ SEMAPHORE_PROXMOX_PASSWORD }}"
        api_host: "{{ SEMAPHORE_PROXMOX_HOST }}"
        vmid: 9999
        state: started
