---
- name: Create Ubuntu VM from template in Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    proxmox_host: "{{ SEMAPHORE_PROXMOX_HOST }}" 
    proxmox_user: "{{ SEMAPHORE_PROXMOX_USER }}"
    proxmox_password: "{{ SEMAPHORE_PROXMOX_PASSWORD }}"
    validate_certs: false
    
  tasks:
    - name: Clone template 105 to new VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: "{{ validate_certs }}"
        
        node: "pve"
        vmid: 9999
        clone: 105
        name: "ubuntu-test-ansible"
        full: yes
        state: present  # <--- BYTT FRÅN "started" TILL "present"
        
      register: clone_result

    - name: Display clone result
      debug:
        var: clone_result

    - name: Start the cloned VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: "{{ validate_certs }}"
        
        node: "pve"
        vmid: 9999
        state: started
        
      register: start_result
      when: clone_result is succeeded

    - name: Display start result
      debug:
        var: start_result
